### ISSUE TITLE
How to use NOverlap component?

### ISSUE THREAD

**Issue by morenonir** [dunnock/react-sigma#2]
In the component file yoo are looking for renderrers. why?

**Comment by dunnock** [comment]
Hi, actually all parameters are optional, rendererIndex is optional and I
supply it only to preserve all functionality that Sigma plugin provides
(sigma allows to use multiple renderers for the same graph, though I did
not add such react extension yet). So in the simplest case NOverlap can be
used as:

```
import { Sigma, NOverlap } from 'react-sigma'
...
<Sigma graph={graph_data}>
  <NOverlap/>
</Sigma>
```

I am working on detailed documentation now, hope to finish tomorrow.

Cheers, Maxim



6 дек. 2016 г. 14:37 пользователь "morenonir" <notifications@github.com>
написал:

In the component file yoo are looking for renderrers. why?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/dunnock/react-sigma/issues/2>, or mute the thread
