### ISSUE TITLE
forked repo saying: sigma is not declared

### ISSUE THREAD

**Issue by leofle** [dunnock/react-sigma#53]
i forked the repo, because there are some sigma changes we need to make, then build with: 
npm run build , then install the repo from our repository, but when it runs we get:
sigma is not declared from the main.js
our files and the files from the official repo are the same.

```
;(function(undefined) {
  'use strict';

  if (typeof sigma === 'undefined')
    throw 'sigma is not declared';
```
i see that we are not even using the dist/react-sigma.js (also not the oficial repo)
some one can help?

**Comment by dunnock** [comment]
This means sigma is not installed in the windows object, this is performed by webpack following this line:
https://github.com/dunnock/react-sigma/blob/master/sigma-src/webpack.config.sigma.js#L32

The script should be triggered by `npm run build` unless you changed build process. What would `npm run build:sigma` output?

Please note, dependency is fork of Sigma.js: https://github.com/dunnock/sigma.js , not the original one since there were changes to plugins and few fixes to add support of webpack. So you would probably need to fork from there.
