### ISSUE TITLE
./node_modules/react-sigma/es/tools.js:4 

### ISSUE THREAD

**Issue by jkolbe** [dunnock/react-sigma#54]
Hi,

When I'm running `npm run build` I am getting an error with one of your files 

```
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file: 
 	./node_modules/react-sigma/es/tools.js:4 

Read more here: http://bit.ly/2tRViJ9
```

**Comment by dunnock** [comment]
That's weird. What is the version of your node?

**Comment by jkolbe** [comment]
node v7.6.0

**Comment by florianboudot** [comment]
Hi, I have the same error when I build my electron app.
My command is :
```
npm run "cross-env NODE_ENV=production IS_ELECTRON=true webpack --config internals/webpack/webpack.prod.babel.js --color -p --progress"
```
The error is : 
```
ERROR in main.0a9f2d5f85de0a9da9b9.js from UglifyJs
Unexpected token: operator (>) [main.0a9f2d5f85de0a9da9b9.js:4184,57]
```
And if I go in this file, there are these code lines : 
```
// CONCATENATED MODULE: ./node_modules/react-sigma/es/tools.js


function embedProps(elements, extraProps) {
  return react_default.a.Children.map(elements, element => react_default.a.cloneElement(element, extraProps)); // this is line 4184
}
```

**Comment by florianboudot** [comment]
Fixed it !

I only updated : 
- `webpack` from `3.5.5` to `3.10.0`
- `electron-builder` from `17.5.0` to `19.49.2`.

But the main change to notice is that it replaced `uglify-js` by `uglify-es` in `uglifyjs-webpack-plugin`.

**Comment by jkolbe** [comment]
pardon my ignorance but how do I update webpack? I was just using create-react-app

**Comment by florianboudot** [comment]
Manually : 
- You change the version number of webpack in your package.json, then delete your `node_modules` folder and reinstall with `npm run i`
or see https://stackoverflow.com/questions/16073603/how-do-i-update-each-dependency-in-package-json-to-the-latest-version

**Comment by chrisflatley** [comment]
We've hit the same problem (not using electron though),  its not just this file I think, that's just the first one it tries...

The bit.ly link takes you to https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify which in effect say that create-react-app is assuming that dependencies in NPM registry (hence in node_modules) are compiled down to ES5. 

According to the create-react-app link, ideally your es/ build would transpile to ES5. I wonder if that was the default output language once in Webpack but now its changed? (Otherwise, from reading that link, I can't see how react-sigma could have ever been built into a create-react-app app ?)

**Comment by djbarnwal** [comment]
@dunnock I am facing a similar situation now. I am using `create-react-app` for one of my projects along with `react-sigma`. I am unable to build the static files using `npm run build`. The error message reads that it was unable to minify the code and linked to this URL - https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify

The link says to publish the code on npm as ES5

**Comment by dunnock** [comment]
Checking history issues. Webpack was updated to 4.10 some time ago, this problem should have disappeared
