### ISSUE TITLE
when I use LoadJSON ,I can see nothing

### ISSUE THREAD

**Issue by liqiuyue1234567** [dunnock/react-sigma#80]
this is my code: 
<Sigma>
                <LoadJSON url="../data/arctic.json"/>   
 </Sigma>

this is console says:
Uncaught SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at XMLHttpRequest.o.onreadystatechange (webpack-internal:///./node_modules/react-sigma/sigma/parsers.json.js:65)

Thank you very much

**Comment by liqiuyue1234567** [comment]
this is my code: 
<Sigma>
                <LoadJSON url="../data/arctic.json"/>
 </Sigma>

**Comment by dunnock** [comment]
@liqiuyue1234567 I cannot see your code, though that seems that your server returns HTML instead of json file. Try to dig in the browser console for contents, myabe it returns 404 page.

**Comment by liqiuyue1234567** [comment]
I think I may have found a problem. I may have used the wrong url in LoadJSON. The URL should not use the local path, right? Can you explain how to use the URL. thank you very much indeed.

**Comment by dunnock** [comment]
@liqiuyue1234567 `path` property makes a relative path from where your page was loaded, in general it should be same as if you would load json right from your main page. If you are using local system folder, usually browsers disallow to open relative resources. Due to that I am usually using python to host pages locally, e.g. following will host your current dir on port 8000:
```python3 -m http.server --cgi 8000```
